### ISSUE TITLE
CSC2: Partial index needs to be defined on a separate line

### ISSUE THREAD

**Issue by nirbhayc** [bloomberg/comdb2#120]
The following command fails:
```
create table t1 { schema { int i int j } keys { "idx"  = i { where j > 10 } } } $$
```
Error:
```
test> create table t1 { schema { int i int j } keys { "idx"  = i { where j > 10 } } } $$
[create table t1 { schema { int i int j } keys { "idx"  = i { where j > 10 } } }] failed with rc -5 OP #3 BLOCK2_SEQV2(824): ERROR at line   0: syntax error: {
```

The partial index definition is expected to be on a separate line. Lifting this limitation by fixing the lexer could be tricky (and potentially error prone). Better move the CSC2 parsing to lemon (as suggested by @akshatsikarwar).

**Comment by mponomar** [comment]
If you're interested, take a look at https://github.com/mponomar/comdb2/tree/remove-csc2
This was a decently complete attempt.  It's missing either glue code to make it look like the dyns* calls we have now (please no) or other integration code to make it callable from tag and friends.  It's from around a year ago, so missing Lingzhi's index changes, but is otherwise much much cleaner than the current lex/yacc code.  At some point I ran this on a chunk of production schemas, and found a couple of incompatibilities, all in things that were unintended in the current csc2 code.

**Comment by riverszhang89** [comment]
Is the issue fixed by https://github.com/bloomberg/comdb2/pull/180?

**Comment by ldennis** [comment]
I can take a look if not fixed already.

**Comment by nirbhayc** [comment]
No, it hasn't. The issue lies in the CSC2 parser which #180 did not touch.

**Comment by ldennis** [comment]
I dont think this is a partial index specific issue.
`create table t1 { schema { int i int j } keys { "idx"  = i } }` also fails for me

**Comment by nirbhayc** [comment]
Thanks @ldennis
