### ISSUE TITLE
Where is the code for master to do validation to prevent write-write, read-write conflict?

### ISSUE THREAD

**Issue by AnDongLi** [bloomberg/comdb2#363]
I guess it must be inside toblock_main_int(), before osql_bplog_commit().
Is there document describe the mapping relation between SQLite command and BPOpCode(Block_xxx)?
What's the record format of WAL? is it BPLog?

**Comment by markhannum** [comment]
Write-write conflicts are handled by forcing every write to increment the record's unique-identifier (we call them genids).  So for two racing updates, the winner performs the update, while the loser returns a verify error: the genid it was attempting to update has been modified.  Read-write conflicts are checked in serializable mode from toblock_main_int->bdb_osql_serial_check.  This code compares the committing transaction's read-sets against any writes that have committed after the committing transaction's start.  If there is a conflict, comdb2 will fail the transaction.

**Comment by AnDongLi** [comment]
Thanks for the reply.
For the write-write conflict detection, is there a function call before commit? or is it handle directly in commit?

**Comment by akshatsikarwar** [comment]
Directly in commit. Losing transaction will fail to find old `genid`.

**Comment by markhannum** [comment]
Write-write conflicts are handled implicitly by forcing updates to modify a record's genid.  Updates use the genid to locate the record being updated, and automatically change the record's genid during the course of the update.  So if two serializable transactions executing at the same point-in-time race to update a record, the winner will change the record's genid (along with whatever other changes were requested), while the loser will fail with a verify error, as it will be unable to find the record that it intended to modify.  Because the loser is executing in the same point-in-time snapshot as the winner, it will never be able to view the winner's changes.

**Comment by akshatsikarwar** [comment]
This applies to all isolation levels (not just serializable)
