### ISSUE TITLE
Can someone explain how btree stripes work?

### ISSUE THREAD

**Issue by AnDongLi** [bloomberg/comdb2#401]
Does one table consist of 8 data files (one for each btree stripes)?
How is one btree partitioned to many subtrees?
When searching in  btrees how cdb layer maintain it like one whole btree?

**Comment by markhannum** [comment]
Stripes are an optimization to improve our insert rate.  Because genids (our global record identifiers) are always increasing, having only a single stripe would cause several concurrent inserters to be serialized by the lock on the stripe's right-most leaf page.  We default to 8 stripes, but you can create databases of up to 16 stripes by setting the DTASTRIPE tunable at database creation time.  Scans access each data file in turn.  Referring indicies use the lowest 4 bits of the record's genid to determine the correct stripe.

**Comment by dorinhogea** [comment]
In case you are wondering why there is a conflict on the right page in the data btree during insert, this is the explanation.  Data btree rows are keyed after genid (a.k.a genid in comdb2 parlay).  Historically, due to its simplicity, genid-s are generated as a monotonical increasing sequence (time or counter).  Therefore the last inserted row will always get in the last page of the btree.
A better genid generation scheme, like using a PRNG instead of time or counter, would spread inserts across the data btree and eliminate the contention.  Something we might consider in the future.
There is one index for a set of stripes, so index lookup avoid the need to look in multiple stripes.

**Comment by AnDongLi** [comment]
Ah my mistake, I kept thinking the btree must be ordered by its key and forgot that the key of data file btree is the genid. Now it makes total sense. 

After reading the code, sqlite book and berkeley db book, got answers from you and running some tests
I feel ready to begin the next step: get invovled into bug fixing, tool development(do you have wireshark plugin to interpret the messages between replicant and master?),etc.
What would you suggest to begin with?

**Comment by AnDongLi** [comment]
Is there a developer mailing list to ask developemnt-related question or is this the place?

**Comment by akshatsikarwar** [comment]
Btree _is_ ordered by key (genid or otherwise). The trick is that we don't fetch records in insert order. Each inserting thread gets stripe affinity and avoids the contention described above.
